# IgniteCyber OpenSOC Roadmap Template
# Import with: gh project create --template .github/project-roadmap-template.yml

name: IgniteCyber OpenSOC Roadmap
description: >
  Central roadmap for building, testing, and launching each OpenSOC module 
  (Modules 0–5), contributor tasks, and community milestones.

# Default layout
layout: board

# Columns (views)
views:
  - type: board
    name: "OpenSOC Build Roadmap"
    description: "Track module progress from planning to completion"
    columns:
      - name: 🟡 Backlog
        description: "Ideas and tasks waiting to be assigned"
      - name: 🟢 In Progress
        description: "Active development or documentation underway"
      - name: 🔵 Review
        description: "Needs peer or mentor review before marking done"
      - name: 🟣 Completed
        description: "Verified and merged into main branch"

# Custom fields for issues
fields:
  - name: Status
    data_type: single_select
    options:
      - Backlog
      - In Progress
      - Review
      - Completed

  - name: Priority
    data_type: single_select
    options:
      - High
      - Medium
      - Low

  - name: Module
    data_type: single_select
    options:
      - Module 0 – SOC Foundations
      - Module 1 – Initial Access
      - Module 2 – Malware Analysis
      - Module 3 – Incident Response
      - Module 4 – Threat Hunting
      - Module 5 – Professional Development
      - Community / Outreach

  - name: Due Date
    data_type: date

  - name: Owner
    data_type: text

# Automation workflows
automation:
  - on: issues.opened
    set:
      field: Status
      value: Backlog
  - on: pull_request.opened
    set:
      field: Status
      value: In Progress

# Example starter tasks (you can delete after importing)
seed_issues:
  - title: "Module 0 – Build SOC Foundations Lab Environment"
    body: |
      Configure Wazuh, Zeek, and Security Onion stack for Module 0.
      - Create Docker Compose configs
      - Validate lab telemetry
      - Document setup in /docs/setup-guides
    labels: ["module: foundations", "documentation"]
    priority: High
    module: "Module 0 – SOC Foundations"

  - title: "Module 1 – Phishing Detection Lab"
    body: |
      Develop initial access simulation with email artifacts and Wazuh detection rules.
      - Include Sigma rule mappings to MITRE ATT&CK T1566
      - Provide sample analysis report template
    labels: ["module: initial-access"]
    priority: Medium
    module: "Module 1 – Initial Access"

  - title: "Community Collaboration Setup"
    body: |
      Connect with SANS Community Chapters for mentorship and contributor onboarding.
      - Add upcoming events to community/sans-chapters.md
      - Invite volunteers to OpenSOC Slack
    labels: ["community"]
    priority: Medium
    module: "Community / Outreach"
