services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    networks:
      - socnet
    environment:
      - PCAP_FILE=${PCAP_FILE:-pcap_log4shell_cve2021_44228_jndi_reference_2022-05-11181020.pcap}
      - RULES_FILE=${RULES_FILE:-local.rules}
    volumes:
      - .:/data:ro
      - ./rules:/etc/suricata/rules:ro
      - ./logs/suricata-logs:/var/log/suricata
    entrypoint: []
    command: ["sh", "-c", "suricata -r /data/$PCAP_FILE -l /var/log/suricata -S /etc/suricata/rules/$RULES_FILE -k none"]
    profiles:
      - suricata

  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    networks:
      - socnet
    environment:
      - PCAP_FILE=${PCAP_FILE:-pcap_log4shell_cve2021_44228_jndi_reference_2022-05-11181020.pcap}
    volumes:
      - .:/data:ro
      - ./logs/zeek-logs:/zeek-logs
    working_dir: /zeek-logs
    entrypoint: []
    command: ["sh", "-c", "zeek -r /data/$PCAP_FILE -w /zeek-logs/processed.pcap -C"]
    profiles:
      - zeek

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0
    container_name: logstash-zeek
    network_mode: host
    volumes:
      - ./logs/zeek-logs:/var/log/zeek:ro
      - ./logstash-zeek.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - [path_to_dir]/IgniteCyber-OpenSOC/ignitecyber-opensoc-labs/stacks/stack-wazuh-endpoint/config/wazuh_indexer_ssl_certs/root-ca.pem:/etc/ssl/root-ca.pem:ro


networks:
  socnet:
    driver: bridge
