services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    networks:
      - socnet
    environment:
      - PCAP_FILE=${PCAP_FILE:-pcap_log4shell_cve2021_44228_jndi_reference_2022-05-11181020.pcap}
      - RULES_FILE=${RULES_FILE:-local.rules}
    volumes:
      - .:/data:ro
      - ./rules:/etc/suricata/rules:ro
      - ./logs/suricata-logs:/var/log/suricata
    entrypoint: []
    command: ["sh", "-c", "suricata -r /data/$PCAP_FILE -l /var/log/suricata -S /etc/suricata/rules/$RULES_FILE -k none"]
    profiles:
      - suricata

  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    networks:
      - socnet
    environment:
      - PCAP_FILE=${PCAP_FILE:-pcap_log4shell_cve2021_44228_jndi_reference_2022-05-11181020.pcap}
    volumes:
      - .:/data:ro
      - ./logs/zeek-logs:/zeek-logs
    working_dir: /zeek-logs
    entrypoint: []
    command: ["sh", "-c", "zeek -r /data/$PCAP_FILE -w /zeek-logs/processed.pcap -C"]
    profiles:
      - zeek

networks:
  socnet:
    driver: bridge
